name: Build edlab manifest

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  build-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Generate coach list
        run: |
          mkdir -p assets
          if [ -d "coach" ]; then
            find coach -maxdepth 1 -type f -name "*.html" | sed 's#^#/#' | sort > /tmp/coach.txt || true
          else
            : > /tmp/coach.txt
          fi

      - name: Generate electric list
        run: |
          if [ -d "elect_II_kyrs" ]; then
            find elect_II_kyrs -maxdepth 1 -type f -name "*.html" | sed 's#^#/#' | sort > /tmp/electric.txt || true
          else
            : > /tmp/electric.txt
          fi

      - name: Build assets/edlab-manifest.json
        run: |
          COACH_JSON=$(jq -R -s 'split("\n")[:-1]' /tmp/coach.txt)
          ELECT_JSON=$(jq -R -s 'split("\n")[:-1]' /tmp/electric.txt)
          jq -n --argjson coach "$COACH_JSON" --argjson electric "$ELECT_JSON" \
            '{coach:$coach, electric:$electric}' > assets/edlab-manifest.json
          echo "Generated assets/edlab-manifest.json:"
          cat assets/edlab-manifest.json

      - name: Commit manifest if changed
        run: |
          if ! git diff --quiet -- assets/edlab-manifest.json; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add assets/edlab-manifest.json
            git commit -m "chore: update edlab-manifest.json"
            git push
          else
            echo "No changes in manifest"
          fi
