name: SEO Autofix & Sitemap

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci || npm i

      - name: Run SEO autofix
        run: npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(seo): autofix meta tags + sitemap.xml"
          title: "SEO autofix: meta tags + sitemap"
          body: |
            Автоматичне оновлення:
            - <title>, <meta name="description">, canonical, OG, JSON-LD
            - lang="uk"
            - sitemap.xml, robots.txt (якщо не було)
          branch: "seo/autofix"
          delete-branch: true
